// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.edu.pku.poplar.domain;

import cn.edu.pku.poplar.domain.PeEst;

privileged aspect PeEst_Roo_JavaBean {
    
    public String PeEst.getGene_id() {
        return this.gene_id;
    }
    
    public void PeEst.setGene_id(String gene_id) {
        this.gene_id = gene_id;
    }
    
    public Integer PeEst.getSsr_nr() {
        return this.ssr_nr;
    }
    
    public void PeEst.setSsr_nr(Integer ssr_nr) {
        this.ssr_nr = ssr_nr;
    }
    
    public String PeEst.getSsr_type() {
        return this.ssr_type;
    }
    
    public void PeEst.setSsr_type(String ssr_type) {
        this.ssr_type = ssr_type;
    }
    
    public String PeEst.getSsr() {
        return this.ssr;
    }
    
    public void PeEst.setSsr(String ssr) {
        this.ssr = ssr;
    }
    
    public Integer PeEst.getSeqSize() {
        return this.seqSize;
    }
    
    public void PeEst.setSeqSize(Integer seqSize) {
        this.seqSize = seqSize;
    }
    
    public Integer PeEst.getSeqStart() {
        return this.seqStart;
    }
    
    public void PeEst.setSeqStart(Integer seqStart) {
        this.seqStart = seqStart;
    }
    
    public Integer PeEst.getSeqEnd() {
        return this.seqEnd;
    }
    
    public void PeEst.setSeqEnd(Integer seqEnd) {
        this.seqEnd = seqEnd;
    }
    
}
