// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.edu.pku.poplar.domain;

import cn.edu.pku.poplar.domain.Pic;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Pic_Roo_Configurable {
    
    declare @type: Pic: @Configurable;
    
}
